### ISSUE TITLE
Architecture

### ISSUE THREAD

**Issue by KenxinKun** [d6o/portsservice#3]
Your implementation has the JSON loader and the API both directly talking with the database layer. How would the architecture look if you wanted to implement multiple APIs using the same core service? How would you scale it?

**Comment by d6o** [comment]
Hi Borja,

To improve scalability and promote reuse, I suggest creating a new layer for use cases that has no dependency on the API. This can be achieved by following these steps:

1. Within the `internal` folder, create a `usecases` package to contain the core logic for different APIs.

2. In the `usecases` package, create a new file called `find_port.go` and move the business logic from `api_get_port.go` into it.

3. Update `get_port.go` to accept an interface and inject the newly created usecase into it.

4. Let's say you need to create a GRPC API. Define an interface in the GRPC handler and inject `usecases/find_port.go` into it.

5. In `app.go`, wire up the new use cases with their respective APIs.

With the APIs interacting with the use case layer, it becomes easier to scale the architecture as needed. You can add new APIs and business logic without affecting the existing implementation.

Introducing the use case layer effectively decouples the APIs from the database layer, allowing for better scalability.

I have created [this PR](https://github.com/d6o/portsservice/pull/7) with the changes above and a quick GRPC implementation.
