### ISSUE TITLE
Types

### ISSUE THREAD

**Issue by KenxinKun** [d6o/portsservice#4]
It seems you've defined a core type for your core domain and re-used it across your architecture. Can you comment on the impact this has when considering different transport mechanisms? (currently you have couple the core type with the JSON definition)

**Comment by d6o** [comment]
Hi Borja,

You've brought up a great point about coupling the core domain type (in this case, the `Port` struct) with JSON definitions. This can indeed have an impact when considering different transport mechanisms. As the architecture currently stands, the `Port` struct is directly coupled to JSON through the use of struct tags. This means that if we wanted to switch to another transport mechanism, such as XML or Protocol Buffers, we would need to modify the `Port` struct, which could introduce potential issues.

To address this concern and make the code more flexible, we can consider implementing a separate Data Transfer Object (DTO) for each transport mechanism. This way, the core domain type, `Port`, can remain agnostic of the transport mechanism being used, and each DTO can handle the conversion to and from the transport-specific format.

I have created [this PR](https://github.com/d6o/portsservice/pull/8) to implement the suggestions above.
